category = models.CharField(unique=False, max_length=50, blank=True, null=True)
    revenue = models.IntegerField(unique=False, blank=True, null=True)
    one_year_target_estimate = models.DecimalField(max_digits=19, decimal_places=10, default=Decimal(0.0000), blank=True, null=True)
    previous_close = models.DecimalField(unique=False, max_digits=19, decimal_places=10, default=Decimal(0.0000), blank=True, null=True)
    open = models.DecimalField(unique=False, max_digits=19, decimal_places=10, default=Decimal(0.0000), blank=True, null=True)
    ask = models.DecimalField(unique=False, max_digits=19, decimal_places=10, default=Decimal(0.0000), blank=True, null=True)
    bid = models.DecimalField(unique=False, max_digits=19, decimal_places=10, default=Decimal(0.0000), blank=True, null=True)
    day_minimum = models.DecimalField(unique=False, max_digits=19, decimal_places=10, default=Decimal(0.0000), blank=True, null=True)
    day_maximum = models.DecimalField(unique=False, max_digits=19, decimal_places=10, default=Decimal(0.0000), blank=True, null=True)
    year_minimum = models.DecimalField(unique=False, max_digits=19, decimal_places=10, default=Decimal(0.0000), blank=True, null=True)
    year_maximum = models.DecimalField(unique=False, max_digits=19, decimal_places=10, default=Decimal(0.0000), blank=True, null=True)
    volume = models.IntegerField(unique=False, blank=True, null=True)
    average_volume = models.IntegerField(unique=False, blank=True, null=True)
    market_cap = models.IntegerField(unique=False, blank=True, null=True)
    beta = models.DecimalField(unique=False, max_digits=19, decimal_places=10, default=Decimal(0.0000), blank=True, null=True)
    PE_ratio = models.DecimalField(unique=False, max_digits=19, decimal_places=10, default=Decimal(0.0000), blank=True, null=True)
    EPS = models.DecimalField(unique=False, max_digits=19, decimal_places=10, default=Decimal(0.0000), blank=True, null=True)
    Earnings_date = models.DateTimeField(auto_now=False, auto_now_add=False)
    FDAY = models.DecimalField(unique=False, max_digits=19, decimal_places=10, default=Decimal(0.0000), blank=True, null=True)
    ex_dividend_date = models.DateTimeField(auto_now=False, auto_now_add=False)
    url = models.CharField(unique=True, max_length=50, blank=True, null=True)
